# Generated by Django 3.1.2 on 2021-08-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('author', models.CharField(max_length=100, verbose_name='Name')),
                ('publication', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Publishable ?')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published at ')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Names',
            },
        ),
    ]
